"""Initial migration - Phase 0 core tables

Revision ID: 3f648335aec0
Revises: 
Create Date: 2025-11-26 03:52:54.236314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f648335aec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index('ux_entities_type_value', 'entities', ['entity_type', 'entity_value'], unique=True)
    op.create_table('raw_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('original_payload', sa.JSON(), nullable=False),
    sa.Column('enrichment_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_alerts_entity_id'), 'raw_alerts', ['entity_id'], unique=False)
    op.create_index('ix_raw_alerts_entity_observed', 'raw_alerts', ['entity_id', 'observed_at'], unique=False)
    op.create_table('threshold_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('analyzer_key', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('comparison', sa.String(length=16), server_default='>=', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threshold_overrides_entity_id'), 'threshold_overrides', ['entity_id'], unique=False)
    op.create_table('normalized_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_alert_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('original_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_alert_id'], ['raw_alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_events_entity_id'), 'normalized_events', ['entity_id'], unique=False)
    op.create_index('ix_normalized_events_entity_observed', 'normalized_events', ['entity_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_normalized_events_event_type'), 'normalized_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_normalized_events_raw_alert_id'), 'normalized_events', ['raw_alert_id'], unique=False)
    op.create_table('entity_risk_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('normalized_event_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_event_id'], ['normalized_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_risk_history_entity_id'), 'entity_risk_history', ['entity_id'], unique=False)
    op.create_index('ix_entity_risk_history_entity_observed', 'entity_risk_history', ['entity_id', 'observed_at'], unique=False)
    op.create_table('tp_fp_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('normalized_event_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_event_id'], ['normalized_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tp_fp_feedback_entity_id'), 'tp_fp_feedback', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tp_fp_feedback_entity_id'), table_name='tp_fp_feedback')
    op.drop_table('tp_fp_feedback')
    op.drop_index('ix_entity_risk_history_entity_observed', table_name='entity_risk_history')
    op.drop_index(op.f('ix_entity_risk_history_entity_id'), table_name='entity_risk_history')
    op.drop_table('entity_risk_history')
    op.drop_index(op.f('ix_normalized_events_raw_alert_id'), table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_event_type'), table_name='normalized_events')
    op.drop_index('ix_normalized_events_entity_observed', table_name='normalized_events')
    op.drop_index(op.f('ix_normalized_events_entity_id'), table_name='normalized_events')
    op.drop_table('normalized_events')
    op.drop_index(op.f('ix_threshold_overrides_entity_id'), table_name='threshold_overrides')
    op.drop_table('threshold_overrides')
    op.drop_index('ix_raw_alerts_entity_observed', table_name='raw_alerts')
    op.drop_index(op.f('ix_raw_alerts_entity_id'), table_name='raw_alerts')
    op.drop_table('raw_alerts')
    op.drop_index('ux_entities_type_value', table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
