"""Add dedupe_hash to raw_alerts for idempotency

Revision ID: ed0abddeb8b3
Revises: 3f648335aec0
Create Date: 2025-11-26 10:19:40.533606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0abddeb8b3'
down_revision: Union[str, None] = '3f648335aec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_alerts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('dedupe_hash', sa.String(length=64), nullable=False, server_default='')
        )
        batch_op.create_index('ux_raw_alerts_dedupe', ['dedupe_hash'], unique=True)
        batch_op.alter_column('dedupe_hash', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_alerts', schema=None) as batch_op:
        batch_op.drop_index('ux_raw_alerts_dedupe')
        batch_op.drop_column('dedupe_hash')
    # ### end Alembic commands ###
